services:

  wiarygodnik-ui:
    build:
      context: wiarygodnik_frontend
    ports:
      - "80:80"
    networks:
      - wiarygodnik
    depends_on:
      - content-analysis-service
      - report-generation-service
      - keycloak

  content-analysis-service:
    build:
      context: content-analysis-service
    image: content-analysis-service:latest
    deploy:
      replicas: 1
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://content-analysis-service-db:5432/content-analysis-service-db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - LOGGING_LOGSTASH_SERVER=logstash:5000
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8888/realms/wiarygodnik
    networks:
      - wiarygodnik
#      - elk_network
    depends_on:
      - content-analysis-service-db
      - rabbitmq

  content-analysis-service-db:
    image: postgres:15
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: content-analysis-service-db
    volumes:
      - content-analysis-service-db:/var/lib/postgresql/data
    networks:
      - wiarygodnik

  report-generation-service:
    build:
      context: report-generation-service
    image: report-generation-service:latest
    deploy:
      replicas: 1
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://report-generation-service-db:5432/report-generation-service-db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - LOGGING_LOGSTASH_SERVER=logstash:5000
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8888/realms/wiarygodnik
    networks:
      - wiarygodnik
#      - elk_network
    depends_on:
      - report-generation-service-db
      - rabbitmq

  report-generation-service-db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: report-generation-service-db
    volumes:
      - report-generation-service-db:/var/lib/postgresql/data
    networks:
      - wiarygodnik

  rabbitmq:
    image: rabbitmq:4.2.1
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - wiarygodnik

  load-balancer:
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./load-balancer/conf.d:/etc/nginx/conf.d
    networks:
      - wiarygodnik
    depends_on:
      - content-analysis-service
      - report-generation-service

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8888
#      KC_HOSTNAME: keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - "8888:8888"
    volumes:
      - ./keycloak:/opt/keycloak/data/import/
    networks:
      - wiarygodnik
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    networks:
      - wiarygodnik

volumes:
  content-analysis-service-db:
  report-generation-service-db:
  keycloak-db:

networks:
  wiarygodnik:
    driver: bridge
#  elk_network:
#    external: true
