export const AnalysisStatus = {
    ANALYSISNG_CONTENT: 'ANALYSING_CONTENT',
    COMPARING_SIMILAR_SOURCES: 'COMPARING_SIMILAR_SOURCES',
    COMPLETED: 'COMPLETED',
    GENERATING: 'GENERATING',
    GENERATED: 'GENERATED',
    FAILED: 'FAILED'
};