export const SentimentType = {
  POSITIVE: "POSITIVE",
  NEUTRAL: "NEUTRAL",
  NEGATIVE: "NEGATIVE",
  ALARMIST: "ALARMIST",
  IRONIC: "IRONIC",
  PERSUASIVE: "PERSUASIVE",
  AGGRESSIVE: "AGGRESSIVE",
  FORMAL: "FORMAL"
}
