server {
    listen 3000;

    location /api/analysis {
        proxy_pass http://content-analysis-service:8081;
    }

    location /api/report {
        proxy_pass http://report-generation-service:8082;
    }

    location / {
        proxy_pass http://wiarygodnik-ui:80;
    }
}