INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (1, 1, 'To zdanie ukazuje odrzucenie lekarzy, co nadaje tekstowi negatywny wydźwięk.', 'Donald Trump całkowicie ignoruje zalecenia lekarzy.');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (2, 2, 'Wzmianka o siniakach i ich przyczynie wywołuje niepokój i alarm o zdrowiu prezydenta.', 'Na jego dłoniach pojawiają się siniaki, które, jak wynika z tłumaczeń Białego Domu, wynikają ze zbyt częstego brania aspiryny, a także... witania się z innymi poprzez ściśnięcie ręki.');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (3, 3, 'Zobowiązanie do powyższego zdania zawiera przesadny ton, sugerujący ironiczny komentarz autora.', 'Genetyka jest bardzo ważna, a ja mam bardzo dobre geny" - ocenił.');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (4, 4, 'Trump wyraża argument, który ma na celu przekonanie czytelników o korzyściach dużych dawek aspiryny.', 'Mówią, że aspiryna jest dobra na rozrzedzanie krwi, a ja nie chcę gęstej krwi przepływającej przez moje serce. Chcę ładnej, rzadkiej krwi przepływającej przez moje serce.');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (5, 5, 'Wykrzyknik i wielkie litery podkreślają radość i ekscytację, co czyni fragmentem wyrazistą celebrację narodzin.', 'Anna Kurnikowa URODZIŁA!');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (6, 5, 'Wypowiedź podkreśla pozytywne wydarzenie oraz udostępnienie zdjęcia, co wzmacnia poczucie szczęścia i nowej rodziny.', 'Enrique Iglesias został ojcem po raz CZWARTY i pokazał ZDJĘCIE dziecka (FOTO)');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (7, 5, 'Szczegółowe opisanie nowego dziecka i wspólnego powitania wywołuje pozytywny nastrój.', 'Późnym poniedziałkowym wieczorem poinformowała jednak w sieci, że razem z Enrique Iglesiasem powitali na świecie nowego członka rodziny.');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (8, 6, 'Wezwanie „ZOBACZ” zachęca czytelnika do aktywnego uczestnictwa i wzbudza ciekawość, co nadaje fragmentowi charakter perswazyjny.', 'ZOBACZ: Anna Kournikova z mocno zaokrąglonym brzuszkiem na zakupach z synem.');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (9, 6, 'Użycie wyrazu „NIE UKRYWA” oraz wezwanie do obejrzenia zdjęcia podkreśla perswazję, zmuszając czytelnika do sprawdzenia informacji.', 'ZOBACZ: 44-letnia Anna Kournikova już NIE UKRYWA ciążowych krągłości (ZDJĘCIA).');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (16, 13, 'Wypowiedź wyraża radość i ekscytację z nowego etapu życia, co stanowi przykład nacechowania pozytywnego.', 'Tak, zaręczyłam się i jestem mega happy');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (17, 14, 'Twardy, krytyczny ton i bezpośrednie oskarżenie wobec komentatorów wskazują na nacechowanie agresywne.', 'NIE MACIE GUSTU!');
INSERT INTO public.sentiment_example_quote (id, sentiment_example_id, explanation, quote) VALUES (18, 15, 'Opisanie reakcji z przśmiewczą miną sugeruje lekki, satyryczny ton, co można zakwalifikować jako ironię.', 'Moja reakcja na wasze tiktoki - podpisała zdjęcie z przśmiewczą miną');

SELECT setval('sentiment_example_quote_seq', (SELECT MAX(id) FROM public.sentiment_example_quote));