INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (1, 'potwierdza, że dąży do "ładnej, rzadkiej" krwi');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (1, 'potwierdza, że siniaki na dłoniach wynikają z przyjmowania aspiryny');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (1, 'potwierdza, że Trump przyjmuje 325 mg aspiryny codziennie, pomimo zaleceń lekarzy');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (2, 'potwierdza, że dąży do "ładnej, rzadkiej" krwi');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (2, 'potwierdza, że Trump przyjmuje 325 mg aspiryny codziennie, pomimo zaleceń lekarzy');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (2, 'potwierdza, że siniaki wynikają z przyjmowania aspiryny');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (3, 'potwierdza, że dąży do "ładnej, rzadkiej" krwi');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (3, 'potwierdza, że siniaki na dłoniach wynikają z przyjmowania aspiryny');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (3, 'potwierdza, że Trump przyjmuje 325 mg aspiryny codziennie, mimo zaleceń lekarzy');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (4, 'dodaje, że siniaki mogą być spowodowane częstym ściskaniem rąk podczas spotkań');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (4, 'częściowo potwierdza, że siniaki wynikają z przyjmowania aspiryny');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (5, 'Ogłoszenie narodzin czwartego dziecka na Instagramie');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (5, 'Dziecko przyszło tuż przed Świętami Bożego Narodzenia');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (5, 'Zobrazowanie wszystkich czterech dzieci');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (6, 'Pokojowe przyjęcie czwartego dziecka');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (6, 'Rozszerzenie rodziny przed świętami');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (7, 'Publikacja ciepłego zdjęcia rodzinnego');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (7, 'Świętowanie narodzin czwartego dziecka');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (15, 'Viki Gabor jest w związku z Giovanniem Trojanek');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (15, 'Ten opis wprost potwierdza, że artystka ma partnera, choć nazwa partnera różni się od Bogdana Trojanek z głównego źródła');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (16, 'Ten relacja kontrastuje z głównym stwierdzeniem o narzeczeństwie i szczęściu');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (16, 'Viki Gabor zawarła ślub z Giovanniem Trojanek');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (17, 'Viki Gabor została małżonką, ślub w stylu romskim');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (17, 'Twierdzi to, że artystka ma już małżeństwo, co nie zgadza się z informacją o narzeczeniu');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (18, 'Bogdan Trojanek opisuje wesele Viki Gabor z Giovanniem Trojanek');
INSERT INTO public.source_facts (comparison_source_facts_id, facts) VALUES (18, 'Podkreśla, że para zawarła małżeństwo i „uciekła” z tradycyjnego obrzędu, co neguje stwierdzenie o narzeczeniu');