INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'krwiołamy');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'Donald Trump');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, '325 mg');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'siniaki');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'genetyka');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'Wall Street Journal');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'zdrowie');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'dłonie');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'aspiryna');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (1, 'Mar-a-Lago');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'prawa prywatności');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'rodzina');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'para');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'tenis');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'Enrique Iglesias');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'muzyka');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'Instagram');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'czwarte dziecko');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'Anna Kournikova');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (2, 'cięża');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (5, 'szczęście');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (5, 'engagement');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (5, 'Viki Gabor');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (5, 'Bogdan Trojanek');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (5, 'narzeczony');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (5, 'Instagram');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (5, 'media');
INSERT INTO public.source_keywords (source_summary_id, keywords) VALUES (5, 'zaślubin');
