"""update content table, changed user_id to report_id

Revision ID: 267ff639f45d
Revises: 0e3352f50b1f
Create Date: 2025-06-15 20:16:23.085560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267ff639f45d'
down_revision: Union[str, None] = '0e3352f50b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_contents', sa.Column('report_id', sa.String(length=50), nullable=True))
    op.drop_column('web_contents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_contents', sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('web_contents', 'report_id')
    # ### end Alembic commands ###
